server:
  port: 3344
spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:sunwenjiu/springcloud-config.git #GitHub上面的git仓库名字
        ####搜索目录 test
          search-paths:
            - springcloud-config
      ####读取分支
      label: master-test
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
config:
  info: test